version: '1'
services:
  app:
    build: ./
    image: cloud-service
    container_name: cloud_service
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_cloud_service
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - /resources/db/changelog
      - /var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql